{
 "title": "OpenCAS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cache", "label": "Cache", "query": { "query": "label_values(ocf_count,device)" } },
   { "name": "cache_name", "label": "Cache device name", "query": { "query": "label_values(ocf_count,device)" } },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values({device=\"$cache\"},domain)"
    }
   },
   {
    "name": "fast",
    "label": "Fast disk",
    "query": {
     "query": "label_values(node_disk_io_time_weighted_seconds_total{domain=\"$domain\"},device)"
    }
   },
   {
    "name": "slow",
    "label": "Slow disk",
    "query": {
     "query": "label_values(node_disk_io_time_weighted_seconds_total{domain=\"$domain\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{domain=\"$domain\", device=\"$cache\", category=~\"requests\", subcategory=\"rd_total\"}) ",
     "legendFormat": "Read (%)"
    },
    {
     "expr": "  scalar(ocf_percentage{domain=\"$domain\", device=\"$cache\", category=~\"requests\", subcategory=\"wr_total\"}) ",
     "legendFormat": "Write (%)"
    }
   ]
  },
  {
   "title": "Read Cache Hits (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(ocf_percentage{domain=\"$domain\", device=\"$cache\", category=~\"requests\", subcategory=\"rd_hits\"}) / (0.001+scalar(ocf_percentage{domain=\"$domain\", device=\"$cache\", category=~\"requests\", subcategory=\"rd_total\"}))  * 100",
     "legendFormat": "Read Hits (%)"
    }
   ]
  },
  {
   "title": "Write Cache Hits (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{domain=\"$domain\", device=\"$cache\", category=~\"requests\", subcategory=\"wr_hits\"}) /   (0.001+scalar(ocf_percentage{domain=\"$domain\", device=\"$cache\", category=~\"requests\", subcategory=\"wr_total\"})) * 100",
     "legendFormat": "Write Hits (%)"
    }
   ]
  },
  {
   "title": "Cache Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{domain=\"$domain\", device=\"$cache\", category=~\"usage\", subcategory=\"occupancy\"}) ",
     "legendFormat": "Occupancy (%)"
    }
   ]
  },
  {
   "title": "OCF Reads (MBps)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{domain=\"$domain\", device=\"$cache_name\"}[1m])/1024/1024",
     "legendFormat": "{{ bdev_name }} Reads"
    }
   ]
  },
  {
   "title": "OCF Writes (MBps)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{domain=\"$domain\", device=\"$cache_name\"}[1m])/1024/1024",
     "legendFormat": "{{ bdev_name }} Writes"
    }
   ]
  },
  {
   "title": "Cache Laundry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ocf_percentage{domain=\"$domain\", category=~\"usage\", subcategory=\"clean\"}",
     "legendFormat": "Clean Lines (%) - {{device}}"
    },
    {
     "expr": "ocf_percentage{domain=\"$domain\", category=~\"usage\", subcategory=\"dirty\"}",
     "legendFormat": "Dirty Lines (%) - {{ device }}"
    }
   ]
  },
  {
   "title": "Blocks written to CAS (4K blocks)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(ocf_count{domain=\"$domain\", device=\"$cache\", category=~\"blocks\", subcategory=\"volume_wr\"}[1m]) ",
     "legendFormat": "{{ bdev_name }} Writes"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Queue Size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Average Request Size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m]) /\r\n (irate(node_disk_read_completed_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m])+0.01)",
     "legendFormat": "{{ device }} Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m]) /\r\n (irate(node_disk_writes_completed_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m])+0.01)",
     "legendFormat": "{{ device }} Write"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{domain=\"$domain\"}[1m]) + avg_over_time(node_memory_Cached_bytes{domain=\"$domain\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{domain=\"$domain\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{domain=\"$domain\"}[1m])))",
     "legendFormat": "Percent Usage (%)"
    },
    {
     "expr": "(avg_over_time(node_memory_MemTotal_bytes{domain=\"$domain\"}[5s]) - (avg_over_time(node_memory_MemFree_bytes{domain=\"$domain\"}[5s]) + avg_over_time(node_memory_Cached_bytes{domain=\"$domain\"}[5s]) + avg_over_time(node_memory_Buffers_bytes{domain=\"$domain\"}[5s])))/1024/1024/1024",
     "legendFormat": "Total Used (GB)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Device Throughput (MBps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{domain=\"$domain\", device=~\"$fast|$slow|$cache_name\"}[1m])",
     "legendFormat": "{{ device }}  Reads"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{domain=\"$domain\", device=~\"$fast|$slow|$cache_name\"}[1m])",
     "legendFormat": "{{ device }}  Writes"
    }
   ]
  },
  {
   "title": "CPU 0 Usage",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 6, "x": 17, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (irate(node_cpu_seconds_total{domain=\"$domain\", mode=~\"system\"}[1m])*100)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{domain=\"$domain\", device=~\"$fast|$slow|$cache_name\"}[1m])",
     "legendFormat": "{{ device }} Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{domain=\"$domain\", device=~\"$fast|$slow|$cache_name\"}[1m])",
     "legendFormat": "{{ device }} Writes"
    }
   ]
  },
  {
   "title": "Latency (us)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{domain=\"$domain\", device=~\"$fast|$slow\"}[5s]) /  (irate(node_disk_reads_completed_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m])+0.01) * 1000 * 1000",
     "legendFormat": "{{ device }}  read lat"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m]) /  (irate(node_disk_writes_completed_total{domain=\"$domain\", device=~\"$fast|$slow\"}[1m])+0.01) * 1000 * 1000",
     "legendFormat": "{{ device }} write lat"
    }
   ]
  },
  {
   "title": "CPU IOWait Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 37 },
   "targets": [
    {
     "expr": " (irate(node_cpu_seconds_total{domain=\"$domain\", mode=~\"iowait\"}[1m])*100)"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",domain=\"$domain\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',domain=\"$domain\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',domain=\"$domain\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",domain=\"$domain\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',domain=\"$domain\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',domain=\"$domain\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{domain=\"$domain\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{domain=\"$domain\"} - node_memory_MemFree_bytes{domain=\"$domain\"} - (node_memory_Cached_bytes{domain=\"$domain\"} + node_memory_Buffers_bytes{domain=\"$domain\"} + node_memory_SReclaimable_bytes{domain=\"$domain\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{domain=\"$domain\"} + node_memory_Buffers_bytes{domain=\"$domain\"} + node_memory_SReclaimable_bytes{domain=\"$domain\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{domain=\"$domain\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{domain=\"$domain\"} - node_memory_SwapFree_bytes{domain=\"$domain\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  }
 ]
}